sudo: required
language: go
env:
  global:
  - NATS_HOST=localhost
  - NATS_PORT=4222
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update -y
- sudo apt-get -yq install docker-ce
before_script:
- docker pull nats
- docker run --rm -d -p $NATS_PORT:$NATS_PORT nats
- go get github.com/mattn/goveralls
script:
- $GOPATH/bin/goveralls -package github.com/$TRAVIS_REPO_SLUG/app/... -service=travis-ci
- docker build -t $TRAVIS_REPO_SLUG .
